# Generated by Django 4.2.4 on 2024-09-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Без названия', max_length=100),
        ),
    ]
