# Generated by Django 4.2.4 on 2024-09-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab1', '0002_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
