# Generated by Django 4.2.4 on 2024-10-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_authuser_alter_category_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
