# Generated by Django 4.2.4 on 2024-10-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_category_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
