# Generated by Django 4.2.4 on 2024-11-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_remove_categoryproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='platform_comission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Комиссия площадки'),
        ),
    ]
