# Generated by Django 4.2.4 on 2024-11-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_product_rejected_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='platform_comission',
            new_name='platform_commission',
        ),
    ]
