# Generated by Django 4.2.4 on 2024-11-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_rename_platform_comission_product_platform_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='platform_commission',
            new_name='platform_comission',
        ),
    ]
